services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./.env

    environment:
      NODE_ENV: production
      PORT: 5000
      UPSTASH_URL: redis://redis:6379

    depends_on:
      - redis

    command: ["node", "dist/server.js"]

    volumes:
      - shared_uploads:/app/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - ./.env

    environment:
      NODE_ENV: production
      UPSTASH_URL: redis://redis:6379

    depends_on:
      - redis

    command: ["node", "dist/jobs/worker.js"]

    volumes:
      - shared_uploads:/app/uploads

volumes:
  redis_data:
  shared_uploads: